-- MySQL Script generated by MySQL Workbench
-- Wed Dec  7 12:37:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ZSPSHOP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ZSPSHOP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ZSPSHOP` DEFAULT CHARACTER SET utf8 ;
USE `ZSPSHOP` ;

-- -----------------------------------------------------
-- Table `ZSPSHOP`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZSPSHOP`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  `is_admin` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZSPSHOP`.`offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZSPSHOP`.`offers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `users_id`),
  CONSTRAINT `fk_offers_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `ZSPSHOP`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZSPSHOP`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZSPSHOP`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `offers_id` INT NOT NULL,
  `offers_users_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `offers_id`, `offers_users_id`, `users_id`),
  CONSTRAINT `fk_orders_offers1`
    FOREIGN KEY (`offers_id` , `offers_users_id`)
    REFERENCES `ZSPSHOP`.`offers` (`id` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ZSPSHOP`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
